version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.0

executors:
  default:
    working_directory: ~/mattermost-api-reference
    docker:
      - image: circleci/node:11.3.0

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run: mkdir -p node_modules
      - run: make build
      - persist_to_workspace:
          root: ~/mattermost-api-reference
          paths:
            - v4/html

  deploy:
    docker:
      - image: 'circleci/python:2.7'
    working_directory: ~/mattermost-api-reference
    steps:
      - attach_workspace:
          at: ~/mattermost-api-reference/
      - run: ls -la ~/mattermost-api-reference/v4/html
      - run: ls -la ~/mattermost-api-reference/v4/html/static
      - aws-s3/copy:
          from: ~/mattermost-api-reference/v4/html/index.html
          to: "s3://api.mattermost.com/"
          arguments: --acl public-read --cache-control "no-cache"
      - aws-s3/copy:
          from: ~/mattermost-api-reference/v4/html/static/favicon.ico
          to: "s3://api.mattermost.com/static/"
          arguments: --acl public-read --cache-control "no-cache"
      - aws-s3/copy:
          from: ~/mattermost-api-reference/v4/html/static/mattermost-openapi-v4.yaml
          to: "s3://api.mattermost.com/static/"
          arguments: --acl public-read --cache-control "no-cache"
      - aws-s3/copy:
          from: ~/mattermost-api-reference/v4/html/static/favicon.ico
          to: "s3://api.mattermost.com/static/"
          arguments: --acl public-read --cache-control "no-cache"
      - aws-s3/copy:
          from: ~/mattermost-api-reference/v4/html/index.html
          to: "s3://api.mattermost.com/v4/"
          arguments: --acl public-read --cache-control "no-cache"
      - aws-s3/copy:
          from: ~/mattermost-api-reference/v4/html/static/mattermost-openapi-v4.yaml
          to: "s3://api.mattermost.com/v4/static/"
          arguments: --acl public-read --cache-control "no-cache"
      - aws-s3/copy:
          from: ~/mattermost-api-reference/v4/html/static/favicon.ico
          to: "s3://api.mattermost.com/v4/static/"
          arguments: --acl public-read --cache-control "no-cache"


workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          context: mattermost-api-reference-s3
          requires:
            - build
          filters:
            branches:
              only: master
